spring:
  application:
    name: onlineshopping
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping
    username: postgres
    password: mdsoln
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  error:
    include-message: always
logging:
  level:
    org.springframework.security: DEBUG
clickSend-username: your-username
clickSend-apiKey: your-apikey

twilio:
  accountSid: ACf4e726131494afe439b5671f43504709
  authToken: e5bde8315f469c5a50bf028e43b4b426
  phoneNumber: your_twilio_phone_number